//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPSIC_Battleship.I18n {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EPSIC_Battleship.I18n.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AI{0}.
        /// </summary>
        public static string AIn {
            get {
                return ResourceManager.GetString("AIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string BtnBack {
            get {
                return ResourceManager.GetString("BtnBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string BtnCancel {
            get {
                return ResourceManager.GetString("BtnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credits.
        /// </summary>
        public static string BtnCredits {
            get {
                return ResourceManager.GetString("BtnCredits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string BtnDefault {
            get {
                return ResourceManager.GetString("BtnDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demo (AI vs. AI).
        /// </summary>
        public static string BtnDemo {
            get {
                return ResourceManager.GetString("BtnDemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string BtnExit {
            get {
                return ResourceManager.GetString("BtnExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host (new game).
        /// </summary>
        public static string BtnHost {
            get {
                return ResourceManager.GetString("BtnHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join.
        /// </summary>
        public static string BtnJoin {
            get {
                return ResourceManager.GetString("BtnJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string BtnNext {
            get {
                return ResourceManager.GetString("BtnNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        public static string BtnPlayOnline {
            get {
                return ResourceManager.GetString("BtnPlayOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solo.
        /// </summary>
        public static string BtnPlaySolo {
            get {
                return ResourceManager.GetString("BtnPlaySolo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        public static string BtnQuit {
            get {
                return ResourceManager.GetString("BtnQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random.
        /// </summary>
        public static string BtnRandom {
            get {
                return ResourceManager.GetString("BtnRandom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string BtnSave {
            get {
                return ResourceManager.GetString("BtnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string BtnSettings {
            get {
                return ResourceManager.GetString("BtnSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EPSIC Battleship
        ///Yannis Burkhalter, 2019.
        /// </summary>
        public static string Credits {
            get {
                return ResourceManager.GetString("Credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host not found!.
        /// </summary>
        public static string ErrHostNotFound {
            get {
                return ResourceManager.GetString("ErrHostNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On Windows 8.1 and below, you need the following DLL: PresentationFramework.Aero2.dll.
        /// </summary>
        public static string ErrMissingPresentationFrameworkAero2DLL {
            get {
                return ResourceManager.GetString("ErrMissingPresentationFrameworkAero2DLL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one of your boats is bigger than the grid..
        /// </summary>
        public static string ErrParamBoatGtGrid {
            get {
                return ResourceManager.GetString("ErrParamBoatGtGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Each value must be separated by a comma..
        /// </summary>
        public static string ErrParamBoatListFormat {
            get {
                return ResourceManager.GetString("ErrParamBoatListFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of &quot;{0}&quot; must be a number between {1} and {2}..
        /// </summary>
        public static string ErrParamNumber {
            get {
                return ResourceManager.GetString("ErrParamNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create a game!.
        /// </summary>
        public static string ErrUnableToCreateTheGame {
            get {
                return ResourceManager.GetString("ErrUnableToCreateTheGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battleship!.
        /// </summary>
        public static string GameTitle {
            get {
                return ResourceManager.GetString("GameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AI Delay.
        /// </summary>
        public static string LabelAIDelay {
            get {
                return ResourceManager.GetString("LabelAIDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boat Size.
        /// </summary>
        public static string LabelBoatSize {
            get {
                return ResourceManager.GetString("LabelBoatSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid Size.
        /// </summary>
        public static string LabelGridSize {
            get {
                return ResourceManager.GetString("LabelGridSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP: {0}.
        /// </summary>
        public static string LabelIP {
            get {
                return ResourceManager.GetString("LabelIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mine Number.
        /// </summary>
        public static string LabelMineNumber {
            get {
                return ResourceManager.GetString("LabelMineNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuclear Bomb Number.
        /// </summary>
        public static string LabelNuclearBombNumber {
            get {
                return ResourceManager.GetString("LabelNuclearBombNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuclear Bomb Range.
        /// </summary>
        public static string LabelNuclearBombRange {
            get {
                return ResourceManager.GetString("LabelNuclearBombRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your name:.
        /// </summary>
        public static string LabelPlayerName {
            get {
                return ResourceManager.GetString("LabelPlayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sonar Number.
        /// </summary>
        public static string LabelSonarNumber {
            get {
                return ResourceManager.GetString("LabelSonarNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to leave?.
        /// </summary>
        public static string MsgConfirmToLeave {
            get {
                return ResourceManager.GetString("MsgConfirmToLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} throws a nuclear bomb into {1}.
        /// </summary>
        public static string MsgPlayerThrowsNuclearBomb {
            get {
                return ResourceManager.GetString("MsgPlayerThrowsNuclearBomb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} use sonar.
        /// </summary>
        public static string MsgPlayerUseSonar {
            get {
                return ResourceManager.GetString("MsgPlayerUseSonar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} wins!.
        /// </summary>
        public static string MsgPlayerWins {
            get {
                return ResourceManager.GetString("MsgPlayerWins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting on another player....
        /// </summary>
        public static string MsgWaitingForAnOpponent {
            get {
                return ResourceManager.GetString("MsgWaitingForAnOpponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The opponent is still placing his ships....
        /// </summary>
        public static string MsgWaitingOnOpponentPlacement {
            get {
                return ResourceManager.GetString("MsgWaitingOnOpponentPlacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To place a boat:
        ///- Select the first case
        ///- Select the last case among the green ones
        ///
        ///Right click to place a mine.
        /// </summary>
        public static string TextSetup {
            get {
                return ResourceManager.GetString("TextSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The AI.
        /// </summary>
        public static string TheAI {
            get {
                return ResourceManager.GetString("TheAI", resourceCulture);
            }
        }
    }
}
